# Generated by Django 5.2.5 on 2025-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='incident_evidence/'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
