# Generated by Django 5.2.5 on 2025-08-27 05:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_incidentreport_evidence_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='evidence_image',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='incident_evidence/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='report.incidentreport')),
            ],
        ),
    ]
