# Generated by Django 5.2.5 on 2025-08-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_incidentreport_evidence_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreport',
            old_name='floor_number',
            new_name='floor_no',
        ),
        migrations.RemoveField(
            model_name='incidentreport',
            name='room_number',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('DRUG_PEDDLING', 'Drug Peddling'), ('THEFT', 'Theft'), ('VIOLENCE', 'Violence'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='area_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20),
        ),
    ]
